### ISSUE TITLE
Version 0.0.7 isn't published.

### ISSUE THREAD

**Issue by nadavye** [llafuente/esprima-ast-utils#3]
Hi,

I wanted to know if there's a reason why version 0.0.7 isn't published in NPM?
The reason is that version 0.0.6 is referencing esprima via github and my customers are having an issue accessing it from some of their machines.

Cheers,
Nadav

**Comment by llafuente** [comment]
I may just forgot...

I added esprima from a repo that don't have a bug...

I will do a fast review and publish a new version asap

**Comment by nadavye** [comment]
OK.
Thanks for the fast response. Highly appreciated :-)
I'm waiting for an update.

**Comment by llafuente** [comment]
I found the problem. `docr` package link to an old esprima-ast version, you may avoid it's installation using "npm i --production"

I cannot `npm publish` right now, I'm behind a corporate proxy madness.
I will this afternoon.

**Comment by llafuente** [comment]
please check now. should be ok.

sry for the delay.
